// Import font packages from Next.js Google Fonts
import { Geist, Geist_Mono } from "next/font/google";
// Geist and Geist_Mono are modern sans-serif and monospace fonts

// Import global CSS styles (includes Tailwind CSS)
import "./globals.css";

// Configure Geist Sans font - used throughout the app
const geistSans = Geist({
  variable: "--font-geist-sans",  // CSS variable name for the font
  subsets: ["latin"],             // Character set to load
});

// Configure Geist Mono font - used for code/monospace text
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata - SEO information for the page
export const metadata = {
  title: "Create Next App",                    // Page title shown in browser tab
  description: "Generated by create next app", // Description for search engines
};

/**
 * RootLayout - The main layout component that wraps all pages
 * This is a server component by default in Next.js 13+
 * 
 * @param {React.ReactNode} children - The page content to display
 */
export default function RootLayout({ children }) {
  return (
    // HTML document structure with English language
    <html lang="en">
      {/* Body element - applies fonts and smooth text rendering */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* All page content is rendered here */}
        {children}
      </body>
    </html>
  );
}


